--create database storeProducts;

--go

Use storeProducts;
go

create table products(
ID INT IDENTITY(1,1) PRIMARY KEY,
NAME VARCHAR(250),
DESCRIPCION VARCHAR(500),
PRICE decimal(8,2),
STOCK int,
CATEGORY_ID INT,
SUPPLIER_ID INT,
ISACTIVE INT DEFAULT 1,
CREATE_DATE DATETIME DEFAULT GETDATE(),
CREATE_USER VARCHAR(25),
MODIF_DATE DATETIME,
MODIF_USER VARCHAR(25)
);

GO

create table category(
ID INT IDENTITY(1,1) PRIMARY KEY,
NAME VARCHAR(250),
DESCRIPCION VARCHAR(500),
ISACTIVE INT DEFAULT 1,
CREATE_DATE DATETIME DEFAULT GETDATE(),
CREATE_USER VARCHAR(25),
MODIF_DATE DATETIME,
MODIF_USER VARCHAR(25)
);


GO

create table supplier(
ID INT IDENTITY(1,1) PRIMARY KEY,
NAME VARCHAR(250),
DESCRIPCION VARCHAR(500),
CONTACT VARCHAR(150),
PHONE VARCHAR(10),
CELLPHONE VARCHAR(10),
EMAIL VARCHAR(100),
ADDRESS VARCHAR(200),
ISACTIVE INT DEFAULT 1,
CREATE_DATE DATETIME DEFAULT GETDATE(),
CREATE_USER VARCHAR(25),
MODIF_DATE DATETIME,
MODIF_USER VARCHAR(25)
);

GO

create table stockMovement(
ID INT IDENTITY(1,1) PRIMARY KEY,
PRODUCT_ID INT,
TYPE VARCHAR(25),
DESCRIPCION VARCHAR(500),
CUANTITY INT,
USER_ID INT,
DESCRIPTION VARCHAR(250),
ISACTIVE INT DEFAULT 1,
CREATE_DATE DATETIME DEFAULT GETDATE(),
CREATE_USER VARCHAR(25),
MODIF_DATE DATETIME,
MODIF_USER VARCHAR(25)
);

GO


create table users(
ID INT IDENTITY(1,1) PRIMARY KEY,
NAME VARCHAR(150),
USER_NAME VARCHAR(25),
PASSWORD VARCHAR(MAX),
ROL_ID INT,
ISACTIVE INT DEFAULT 1,
CREATE_DATE DATETIME DEFAULT GETDATE(),
CREATE_USER VARCHAR(25),
MODIF_DATE DATETIME,
MODIF_USER VARCHAR(25)
);

GO

create table role(
ID INT IDENTITY(1,1) PRIMARY KEY,
NAME VARCHAR(150),
ISACTIVE INT DEFAULT 1,
CREATE_DATE DATETIME DEFAULT GETDATE(),
CREATE_USER VARCHAR(25),
MODIF_DATE DATETIME,
MODIF_USER VARCHAR(25)
);

GO

CREATE TABLE UserSessions (
    SessionId UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    UserId INT NOT NULL,
    Token VARCHAR(255) NOT NULL,
    IPAddress VARCHAR(45) NULL, -- Soporta IPv4 e IPv6
    UserAgent TEXT NULL,
    StartTime DATETIME NOT NULL DEFAULT GETDATE(),
    EndTime DATETIME NULL,
	isactive INT DEFAULT 1,
	CREATE_DATE DATETIME DEFAULT GETDATE(),
	CREATE_USER VARCHAR(25),
	MODIF_DATE DATETIME,
	MODIF_USER VARCHAR(25)
);

GO

ALTER TABLE products add foreiGN key(CATEGORY_ID) references category(ID);
ALTER TABLE products add foreiGN key(SUPPLIER_ID) references supplier(ID);
ALTER TABLE stockMovement add foreiGN key(USER_ID) references users(ID);
ALTER TABLE stockMovement add foreiGN key(PRODUCT_ID) references products(ID);
ALTER TABLE users add foreiGN key(ROL_ID) references role(ID);
ALTER TABLE UserSessions add foreiGN key(UserId) references users(ID);




CREATE LOGIN [DESKTOP-1PAD0L9\nmena] FROM WINDOWS;
USE storeProducts;
CREATE USER [DESKTOP-1PAD0L9\nmena] FOR LOGIN [DESKTOP-1PAD0L9\nmena];
ALTER ROLE db_owner ADD MEMBER [DESKTOP-1PAD0L9\nmena];

CREATE LOGIN miUsuario WITH PASSWORD = '1qaz.mena';



